/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mydigitalschool.tp4;

import org.mydigitalschool.interaction.InterfaceInteraction;
import org.mydigitalschool.manager.FirebaseManager;

public class App {
	
	
	public static String uid;
	public static String name;
	
    public static void main(String[] args) {
    	FirebaseManager dbManager = new FirebaseManager();
    	InterfaceInteraction interfaceInteraction = new InterfaceInteraction(dbManager);
    	interfaceInteraction.execute();
    			
    }
}
